server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/journal_db
    username: postgres
    password: 123
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret-key: dniprotestsecret
  exp:
    hours: 1